name: Week 5 Assignment Grade

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-grade:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Lint
        id: lint
        continue-on-error: true
        run: npm run lint
      - name: Prettier
        id: prettier
        continue-on-error: true
        run: npm run prettier
      - run: npm test
      - name: Output Test Summary
        if: success() || failure()
        run: npm run ci >> $GITHUB_STEP_SUMMARY
        env:
          LINT_PASSED: ${{ steps.lint.outcome == 'success' }}
          PRETTIER_PASSED: ${{ steps.prettier.outcome == 'success' }}
